name = "Kat Technic"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2ea6b0f91550248a3f57f13290e3f73de58edd1dd81341a12653798fa2d8082"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
