name = "kagpack"
author = "kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dd940d5b599454600ffb64999315f9ed503286d3e0e33da11ebaccd3211955f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
