name = "Arka Modpack"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40cd337df867c6e94bf4d8a756ba6b59747f350d8db8950dd96915ac982626ca"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
