name = "Arka Modpack"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3a2300c9042c62c75fae91909f2265e845d2774af357a792e7fa7e87d41b459"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
