name = "Arka Modpack"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a15e98325c69548c25950cc07b92c196052403b36de8d154329a347b646ef65"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
