name = "kagpack"
author = "kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "846d5a90f299f5d18d0f626a5ee9e4ad7e38f1758d1bd1423b7a8e3df97035eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
