name = "Arka Modpack"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c51b95eff0c68eb7bbbc796bae4c4cc6b955beda663e0909821494d3a1c72329"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
