name = "Kat Technic"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f3cb9299bfdd64fdd3c1339a3c4a215f2075d4ecabd84a2c7f7c45eb03001a8"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
