name = "Arka Modpack"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6596e8d3d656e71b348ed97ce81de3863824619bb5da8c612223224adb7cead0"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
