name = "Kat Technic"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7aada4f9a1111c2bd2d68c3e2aa2e69410f01b589c33f10b9a296d97da3be22"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
