name = "kagpack"
author = "kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "883db6fd45397a1f445ddeefc8ea69e0d578ec308092cac328b26d17b4b63297"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
