name = "Kat Technic"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7b559603279dac27c53f91a0019cfd77261e812acc2c2b761548a5781b74e6"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
