name = "Arka Modpack"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67c1dda53a6218660c51cbdcb43045fde3fa22d74967ee47cba16d3b41ca8ae2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
