name = "Arka Modpack"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ec1abd7b8598f166abc1acecaa804062391d1d929f6539f1ea871eedd9f4282"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
