name = "Kat Technic"
author = "Kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "698ad107ce036b8f1f829590b6bbefd49bcdf27afcf2bbb833d18e7a6b5056e5"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
