name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d868a96f241a7ba624bdf3f82dd869f15d3d734f5d2abb1cd3acd5d863a49d8"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
