name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a133935aba960f807ada24e68602c7a164117974c46604343721566049ae7c4"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
