name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c026dffce647967f2b272b828719206c7698c1a7c2489bb670008aa309a8c0c"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
