name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2f698ff7a17461a3d7ecc044a8614003a62e138ded622b96f6afd04271ce5b3"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
