name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4ec652a92c25dea408ab51d9bbbf6284813a09c11434af0337fb044711e17b8"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
