name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0465d47531bff562abcd0ee84106915410e3a043b5f83f048ce6d753b4fbf42"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
