name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "518020fbf92892741f9f2549cf633e9c8b659a0aeedbb5461cf0d2592e0ddeac"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
