name = "kagpack"
author = "kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0cf74c3de3c5d28a93f44ac0d9a7edab09787af4a84cc2ab0e45a2079e96078"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
