name = "kagpack"
author = "kat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2c1b14e40bfccf4f69dfa6c2588206a5851d3187837a0035fdf7c3caa3207a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
