name: Publish pages site

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get commit message
        id: commit_message
        run: ./build/get-commit-description.sh
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: ${{ steps.commit_message.outputs.COMMIT_SUBJECT }}
          embed-description: ${{ steps.commit_message.outputs.COMMIT_BODY }}
          embed-url: ${{ steps.commit_message.outputs.COMMIT_URL }}
      - name: Run build shell script
        run: ./build/build-github-pages.sh
